sudo: required

services:
  - docker

before_install:
  - docker build -t moudud/docker-react -f Dockerfile.dev .

script:
  - docker run moudud/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: ""
#   bucket_path: ""
#   on:
#     branch: master
#   access_key_id: "$ACCESS_KEY"
#   secret_access_key:
#     secure: "$SECRET_KEY"